on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 * * 1
  push:
    branches: master
    paths:
      - "scripts/dependency-check.sh"
      - ".github/workflows/dependency-check.yml"
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - run: yarn install
      - run: yarn dependency-check
