on:
  schedule:
    - cron: 0 13 * * 1
  push:
    branches: master
    paths:
      - 'dependency-check.sh'
      - '.github/workflows/dependency-check.yml'
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn dependency-check
