on:
  workflow_dispatch:
    inputs:
      upgradeLevel:
        description: "Upgrade level"
        default: "minor"
  schedule:
    - cron: 0 13 * * 1
  push:
    branches: master
    paths:
      - "scripts/dependency-check.sh"
      - ".github/workflows/dependency-check.yml"
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: ./scripts/dependency-check.sh
