on:
  push:
    tags:
      - 'v[0-9]*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
      - run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.npm_token}}
