name: publish
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]*"
jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: [build]
    environment: publish
    permissions:
      contents: write # release
      id-token: write # provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.build.outputs.artifact-id }}
          path: ./artifacts/package.tgz
      - run: npm publish --provenance --access public ./artifacts/package.tgz
      - run: gh release create --verify-tag "v$(jq -r .version package.json)"
        env:
          GH_TOKEN: ${{ github.token }}
